workflows:
  ios-ad-hoc:
    name: iOS Ad Hoc Build for Sideloadly
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          cd .
          flutter pub get
      - name: Build iOS IPA
        script: |
          cd .
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - keitgaoussou@yahoo.com
        notify:
          success: true
          failure: true
